GestionColegioMVC/Controllers/MatriculasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionColegioMVC.Models;

namespace GestionColegioMVC.Controllers
{
    public class MatriculasController : Controller
    {
        private DireccionColegio_DBEntidades db = new DireccionColegio_DBEntidades();

        // GET: Matriculas
        public async Task<ActionResult> Index()
        {
            var matriculas = db.Matriculas.Include(m => m.Curso).Include(m => m.Estudiante).Include(m => m.Profe);
            return View(await matriculas.ToListAsync());
        }

        // GET: Matriculas/Detalles/5
        public async Task<ActionResult> Detalles(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matricula matricula = await db.Matriculas.FindAsync(id);
            if (matricula == null)
            {
                return HttpNotFound();
            }
            return View(matricula);
        }

        // GET: Matriculas/Crear
        public ActionResult Crear()
        {
            ViewBag.IdCurso = new SelectList(db.Cursoes, "IdCurso", "Titulo");
            ViewBag.IdEstudiante = new SelectList(db.Estudiantes, "IdEstudiante", "Nombre", "Apellido");
            ViewBag.IdProfe = new SelectList(db.Profes, "IdProfe", "Nombre", "Apellidos");
            return View();
        }

        // POST: Matriculas/Create
        // Para protexer de ataques de overposting, activa as propiedades especificas coas que queres asociar os elementos da base de datos,
        // mais detalles aqui https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Crear([Bind(Include = "IdMatricula,Nota,IdCurso,IdEstudiante,IdProfe")] Matricula matricula)
        {
            var estaMatriculado = db.Matriculas.Any(q => q.IdCurso == matricula.IdCurso && q.IdEstudiante == matricula.IdEstudiante); //se a IdCurso e a IdEstudiante na matricula coinciden 
            //cun valor que xa hai, isto e verdadeiro, 
            //co cal debemos advertir que ese/a estudiante xa esta matriculado/a
            if (ModelState.IsValid && !estaMatriculado) //tamen vale estaMatriculado == false
            {
                db.Matriculas.Add(matricula);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.IdCurso = new SelectList(db.Cursoes, "IdCurso", dataTextField: "Titulo", matricula.IdCurso);
            ViewBag.IdEstudiante = new SelectList(db.Estudiantes, "IdEstudiante", "Nombre", "Apellido", matricula.IdEstudiante);
            ViewBag.IdProfe = new SelectList(db.Profes, "IdProfe", "Nombre", "Apellidos", matricula.IdProfe);
            //return Json(new { IsSuccess = false, Message = "Estudiante non se engadiu con exito por non estar rexistrado na base de datos ou por estar xa matriculado noutro curso" }, JsonRequestBehavior.AllowGet);//se falla o anterior o programa pasa a estal inea indicando que algo fallou
            return View(matricula);
        }

        // GET: Matriculas/Editar/5
        public async Task<ActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matricula matricula = await db.Matriculas.FindAsync(id);
            if (matricula == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCurso = new SelectList(db.Cursoes, "IdCurso", dataTextField: "Titulo", matricula.IdCurso);
            ViewBag.IdEstudiante = new SelectList(db.Estudiantes, "IdEstudiante", "Nombre", "Apellido", matricula.IdEstudiante);
            ViewBag.IdProfe = new SelectList(db.Profes, "IdProfe", "Nombre", "Apellidos", matricula.IdProfe);
            return View(matricula);
        }

        // POST: Matriculas/Editar/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Editar([Bind(Include = "IdMatricula,Nota,IdCurso,IdEstudiante,IdProfe")] Matricula matricula)
        {
            if (ModelState.IsValid)
            {
                db.Entry(matricula).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.IdCurso = new SelectList(db.Cursoes, "IdCurso", dataTextField: "Titulo", matricula.IdCurso);
            ViewBag.IdEstudiante = new SelectList(db.Estudiantes, "IdEstudiante", "Nombre", "Apellido", matricula.IdEstudiante);
            ViewBag.IdProfe = new SelectList(db.Profes, "IdProfe", "Nombre", "Apellidos", matricula.IdProfe);
            return View(matricula);
        }

        // GET: Matriculas/Eliminar/5
        public async Task<ActionResult> Eliminar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matricula matricula = await db.Matriculas.FindAsync(id);
            if (matricula == null)
            {
                return HttpNotFound();
            }
            return View(matricula);
        }

        // POST: Matriculas/Eliminar/5
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Matricula matricula = await db.Matriculas.FindAsync(id);
            db.Matriculas.Remove(matricula);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionColegioMVC/Views/MatriculasExperimental/Crear.cshtml
@model GestionColegioMVC.Models.Matricula

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--Aqui usaremos un funcion de autocomplete de jqueryui basada en Ajax para k busque detalles de estudiantes na base de datos e facilitar o autocompletado-->
<script>
    $(function () {

        function CargarMatriculas(idc) {
            $.ajax({
            url: '@Url.Action("_matriculasPartial", "Matriculas")',
            dataType: 'html',
            contentType: 'application/html; charset=utf-8',
            type: 'GET',
            data: {
                idCurso: idc
            },
            success: function (data) { //poblamos o div identificado como data con esta funcion
                $('#data').fadeOut().html(data).fadeIn; //crea efectos animados que quedan ben
            }
        });
        }

        var idc = $('#IdCurso').val(); //obten o valor seleccionado actualmente na vista parcial
        CargarMatriculas(idc);

         $('#IdCurso').change(function () {
        var idc = $('#IdCurso').val();
             CargarMatriculas(idc);
             $("#failed").fadeOut('fast');
             $("#success").fadeOut('fast');
    });

        $("#Estudiante_Nombre").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "/Matriculas/GetEstudiantes",
                    dataType: "json",
                    type: "POST", //indicamos que queremos facer un post e non un get
                    data: {
                        term: request.term
                    },
                    success: function (data) {
                        console.log(data);
                        response($.map(data, function (item) {
                            return { label: item.Nombre, value: item.Nombre, id: item.Id }; //map mapea os elementos que lle enviamos en forma de array na funcion GetEstudiantes, e usa esa lista para buscar o nome e Id
                        }))
                    }
                });
            },
            minLength: 2,
            select: function (event, query) {
                console.log(query);
                $("IdEstudiante").val(query.item.id);//isto cambia a Id de Estudiante en tempo real para que se actualize cada vez que cambiamos de estudiante na lista desplegable, senon na consola do navegador non vemos o cambio en tempo real
            }
        });
    });

    function Added(res) {
        if (res.IsSuccess) {
            $(function () {
                $("#failed").fadeOut('fast');
                $("#success").fadeIn('fast');
                //$('#success').append(res.Message); Pode substituir o div que fixemos na paxina
                var idc = $('#IdCurso').val();
                 $.ajax({
                url: '@Url.Action("_matriculasPartial", "Matriculas")',
                dataType: 'html',
                contentType: 'application/html; charset=utf-8',
                type: 'GET',
                data: {
                    idCurso: idc
                },
                success: function (data) { //poblamos o div identificado como data con esta funcion
                    $('#data').fadeOut().html(data).fadeIn; //crea efectos animados que quedan ben
                }
            });
            })
        }
        else {
            Failed(res);
        }
    }

    function Failed(res) {
        if (!res.IsSuccess) {
            $(function () {
               $("#failed").fadeIn('fast');
               $("#success").fadeOut('fast');
            })
        }
    }

    function Failure() {
        $(function () {
            $("#failed").fadeIn('fast');
        })
    }

</script>

<h2>Matricular estudiante</h2>

<!--Aqui usaremos Ajax para non salir da paxina cada vez que agreguemos estudiantes a cursos na matricula-->
@using (Ajax.BeginForm("AgregarEstudiante", "Matriculas", new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "Added",
    OnFailure = "Failure"
}))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Matricula</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <!--Nota e profesores non e conveniente telos aqui, pero si o curso e o estudiante ou estudiantes asignadxs a esa clase-->
    @*<div id="failed" class="alert alert-danger" style="display: none;">
            Houbo un erro engadindo o estudiante oa curso.
        </div>
        <div id="success" class="alert alert-success" style="display: none;">
            Estudiante engadido con exito.
        </div>
    *@
    <div class="form-group">
        <label for="IdCurso" class="control-label col-md-2">Curso</label>
        @Html.LabelFor(model => model.IdCurso, "IdCurso", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("IdCurso", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCurso, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="IdCurso" class="control-label col-md-2">Curso</label>
        @Html.LabelFor(model => model.IdCurso, "IdCurso", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("IdCurso", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCurso, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="Estudiante_Nombre" class="control-label col-md-2">Nome estudiante</label>
        <div class="col-md-10">
            <!--Orixinalmente aqui habia un codigo Html.DropDownList("IdEstudiante", null, htmlAttributes: new { arroba_class = "form-control" }) pero quitamolo para colocar un Textbox e un campo oculto que xenerara o script jquery de arriba -->
            @Html.EditorFor(model => model.Estudiante.Nombre, new { htmlAttributes = new { @class = "form-control" } }) <!--tamen poderiamos usar TextBoxFor-->
            @Html.HiddenFor(model => model.IdEstudiante) <!--A xente na web non ten porque ver a Id de Estudiante, non teria sentido, por iso a escondemos-->
            @Html.ValidationMessageFor(model => model.IdEstudiante, "", new { @class = "text-danger" })
        </div> <!--As dropdown lists son porque se trata de relacions de 1 a moitos co cal podemos seleccionar vari@s estudiantes e demais-->
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Matricular estudiante" class="btn btn-success btn-block" />
        </div>
    </div>
</div>
}

<hr />

<!--Vista parcial, ou sexa, unha vista dentro dunha vista-->
<div id="data">
    @*@Html.Action("_matriculasPartial", "Matriculas")*@
</div>

<div>
    @Html.ActionLink("Volver a lista", "Index")
</div>

GestionColegioMVC/Views/MatriculasExperimental/Detalles.cshtml
@model GestionColegioMVC.Models.Matricula

@{
    ViewBag.Title = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Datos de matricula</h2>

<div>
    <h4>Matricula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Curso.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Curso.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estudiante.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estudiante.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Profe.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profe.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.IdMatricula }) |
    @Html.ActionLink("Volver a lista", "Index")
</p>

GestionColegioMVC/Views/MatriculasExperimental/Editar.cshtml
@model GestionColegioMVC.Models.Matricula

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar matricula</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Matricula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdMatricula)

        <div class="form-group">
            @Html.LabelFor(model => model.Nota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCurso, "IdCurso", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdCurso", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCurso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdEstudiante, "IdEstudiante", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdEstudiante", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdEstudiante, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdProfe, "IdProfe", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProfe", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProfe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a lista", "Index")
</div>

GestionColegioMVC/Views/MatriculasExperimental/Eliminar.cshtml
@model GestionColegioMVC.Models.Matricula

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Borrar matricula</h2>

<h3>Estas seguro/a de que queres eliminar esta matricula?</h3>
<div>
    <h4>Matricula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Curso.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Curso.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estudiante.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estudiante.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Profe.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profe.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Volver a lista", "Index")
        </div>
    }
</div>

GestionColegioMVC/Views/MatriculasExperimental/Index.cshtml
@model IEnumerable<GestionColegioMVC.Models.Matricula>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Paxina principal de matriculas</h2>

<p>
    @Html.ActionLink("Crear nova matricula", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nota)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Curso.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estudiante.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Profe.Nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nota)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Curso.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estudiante.Apellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Profe.Nombre)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.IdMatricula }) |
            @Html.ActionLink("Detalles", "Detalles", new { id=item.IdMatricula }) |
            @Html.ActionLink("Eliminar", "Eliminar", new { id=item.IdMatricula })
        </td>
    </tr>
}

</table>

GestionColegioMVC/Views/MatriculasExperimental/_matriculasPartial.cshtml
@model IEnumerable<GestionColegioMVC.Models.Matricula>

@if (Model.Count() < 1)
{
    <h1 class="text-center text-info">NON HAI MATRICULAS NESTE CURSO</h1>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Curso.Titulo)
            </th>
            <th>
                Nome de estudiante
            </th>
            <th>Accion</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nota)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Curso.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estudiante.Nombre) @Html.DisplayFor(modelItem => item.Estudiante.SegundoNombre) @Html.DisplayFor(modelItem => item.Estudiante.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Profe.Nombre)
                </td>
                <td>
                    @Html.ActionLink("Eliminar", "Eliminar", new { id = item.IdMatricula })
                </td>
            </tr>
        }

    </table>
}