GestionColegioMVC/Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionColegioMVC.Models;

namespace GestionColegioMVC.Controllers
{
    //[Authorize] //restrinxe as opcions de ver ou usar certos controles a determinados usuarios en TODO este controller
    public class CursosController : Controller
    {
        private DireccionColegio_DBEntidades db = new DireccionColegio_DBEntidades();

        // GET: Cursos
        public ActionResult Index()
        {
            return View(db.Cursoes.ToList());
        }

        // GET: Cursos/Details/5
        public ActionResult Detalles(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.Cursoes.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // GET: Cursos/Create
        public ActionResult Crear()
        {
            return View();
        }

        // POST: Cursos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear([Bind(Include = "IdCurso,Titulo,Creditos")] Curso curso)
        {
            if (ModelState.IsValid) //se os datos son validos, gardanse e volvemos o inicio
            {
                db.Cursoes.Add(curso);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(curso); //se os datos non son validos (nome moi largo, numeros demasiado grandes, etc) volve a mostrarnos a vista na que estabamos sen cambio na inclusion de datos
        }

        // GET: Cursos/Edit/5
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.Cursoes.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // POST: Cursos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "IdCurso,Titulo,Creditos")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                db.Entry(curso).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(curso);
        }

        // GET: Cursos/Delete/5
        public ActionResult Eliminar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.Cursoes.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // POST: Cursos/Delete/5
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Curso curso = db.Cursoes.Find(id);
            db.Cursoes.Remove(curso);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionColegioMVC/Controllers/EstudiantesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionColegioMVC.Models;

namespace GestionColegioMVC.Controllers
{
    //[Authorize(Roles = "Profe, Admin")] //restriccion para TODO este controlador, para que non todo o mundo poida ver todas as opcions de estudiantes, neste caso solo as poderan ver os Admins e Profesorado
    public class EstudiantesController : Controller
    {
        private DireccionColegio_DBEntidades db = new DireccionColegio_DBEntidades();

        // GET: Estudiantes
        [AllowAnonymous] //Aqui rectificamos Authorize para permitir que calquera persona poida ver a lista de estudiantes pero se non esta rexistrada, non pode crear matricula e demais
        public async Task<ActionResult> Index()
        {
            return View(await db.Estudiantes.ToListAsync());
        }

        // GET: Estudiantes/Detalles/5
        public async Task<ActionResult> Detalles(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estudiante estudiante = await db.Estudiantes.FindAsync(id);
            if (estudiante == null)
            {
                return HttpNotFound();
            }
            return View(estudiante);
        }

        // GET: Estudiantes/Crear
        public ActionResult Crear()
        {
            return View();
        }

        // POST: Estudiantes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Crear([Bind(Include = "IdEstudiante,Apellido,Nombre,FechaMatriculacion,SegundoNombre")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                db.Estudiantes.Add(estudiante);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(estudiante);
        }

        // GET: Estudiantes/Editar/5
        public async Task<ActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estudiante estudiante = await db.Estudiantes.FindAsync(id);
            if (estudiante == null)
            {
                return HttpNotFound();
            }
            return View(estudiante);
        }

        // POST: Estudiantes/Editar/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Editar([Bind(Include = "IdEstudiante,Apellido,Nombre,FechaMatriculacion,SegundoNombre")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estudiante).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(estudiante);
        }

        // GET: Estudiantes/Borrar/5
        public async Task<ActionResult> Eliminar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estudiante estudiante = await db.Estudiantes.FindAsync(id);
            if (estudiante == null)
            {
                return HttpNotFound();
            }
            return View(estudiante);
        }

        // POST: Estudiantes/Borrar/5
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Estudiante estudiante = await db.Estudiantes.FindAsync(id);
            db.Estudiantes.Remove(estudiante);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionColegioMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionColegioMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "A paxina de descripcion da aplicacion.";

            return View();
        }

        public ActionResult Contacto()
        {
            ViewBag.Message = "As nosas formas de contacto.";

            return View();
        }

        public ActionResult VistaTesteo()
        {
            return View();
        }
    }
}

GestionColegioMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "Sobre Nos";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GestionColegioMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GestionColegioMVC/Views/Home/Contacto.cshtml
@{
    ViewBag.Title = "Contacto";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GestionColegioMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Web principal";
}

<div class="jumbotron">
    <h1>IES de TEIS</h1>
    <p class="lead">O IES de Teis... Esta maxestuosa institucion e un instituto no que podes alcanzar grandes metas para crear excelentes programas e sitios web aprendendo a utilizar HTML, CSS, e outras linguaxes de programacion. Matriculate. Esperamoste cos brazos abertos e as personas semientornadas</p>
    <p><a href="http://www.edu.xunta.gal/centros/iesteis/" class="btn btn-primary btn-lg">Aprende mais &raquo;</a></p>
</div>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicatores do carousel -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper para imaxes estilo diapositiva -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/Content/Imaxes/diapositiva1.jpg" alt="Aqui aprendemos">
            <div class="carousel-caption">
                <span>Aqui aprendemos!</span>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/Imaxes/diapositiva2.png" alt="Nunca pares de aprender">
            <div class="carousel-caption">
                <span>Nunca pares de aprender</span>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/Imaxes/diapositiva3.jpg" alt="Ganamos tod@s">
            <div class="carousel-caption">
                <span>Ganamos tod@s</span>
            </div>
        </div>
    </div>

    <!-- Controles do carousel -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Cursos</h2>
        <p>
            Cursos ós que podes apuntarte e a nosa oferta educativa, basada en crear o millor contido, sitios dinamicos, con  control absoluto para unha matriculacion axil e disfrutable.
        </p>
        <p>@Html.ActionLink("Mais informacion","Index", "Cursos", new {@class="btn btn-primary"})</p>
    </div>
    <div class="col-md-6">
        <h2>Estudiantes</h2>
        <p>Obten a millor educacion queridx estudiante. Aqui podes ver quenes estaran contigo nesta aventura do saber na nosa santa institucion</p>
        <p>@Html.ActionLink("Todxs xs estudiantes", "Index", "Estudiantes", new {@class="btn btn-info"})</p>
    </div>
</div>

GestionColegioMVC/Views/Home/VistaTesteo.cshtml
@{
    ViewBag.Title = "VistaTesteo";
}

<h2>VistaTesteo</h2>

<p class="text-info">Hola</p>